# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 16:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_profile',
            field=jsonfield.fields.JSONField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_settings',
            field=jsonfield.fields.JSONField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_location',
            field=jsonfield.fields.JSONField(default='', max_length=1000),
        ),
    ]
