branch-defaults:
  default:
    environment: papr-be-dev-20170810
    group_suffix: null
global:
  application_name: papr_be
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-papr
  repository: null
  sc: null
  workspace_type: Application
